name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}] # setiap hari
  workflow_dispatch:             # bisa dijalankan manual

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          base: activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_stars: yes
          plugin_followup: yes
          plugin_achievements: yes
